## Create random numbers

The `random` subpackage of `numpy` can be used to generate random numbers:

- float values in $[0, 1[$
- integers


In [2]:
import numpy.random as npr

In [6]:
npr.random((2, 5))       

array([[0.81766694, 0.14319621, 0.24420405, 0.79485374, 0.36446199],
       [0.62801431, 0.16768836, 0.31869047, 0.91741838, 0.48900763]])

In [7]:
npr.randint(1, 10, (8, 3))   # (8, 3) integers in [1, 10[ (10 excluded)

array([[2, 1, 8],
       [4, 8, 4],
       [2, 6, 2],
       [1, 9, 2],
       [7, 7, 9],
       [1, 1, 8],
       [9, 9, 1],
       [4, 4, 2]])

Random numbers can also be generated following specific statistical distribution:

In [8]:
print(npr.uniform(0, 5, (3, 4)))                 # uniform probability of a number in [0, 5], 
                                                 # with shape (3, 4)
print(npr.normal(loc=0, scale=5, size=(3, 4)))   # normal probability with mu=0 and std=5,
                                                 # with shape=(3, 4)

[[1.99681708 2.79904736 2.17633328 1.49729344]
 [4.11716777 4.92349861 0.21887788 0.75476233]
 [2.885842   1.27164751 3.66103527 1.56154697]]
[[ 7.26234311 -4.04165132 -0.50045676  1.06735817]
 [-3.21492431  0.59875201  4.56122662 -5.31195884]
 [-1.54579796 -5.27946634  4.55081793  1.30889338]]


## Create deterministic random

The scientific approach needs reproducible computation steps. Whenever these steps imply random number generation, this can leads to problems: values differ from one execution to another.

In [9]:
my_physical_variable = npr.random(4)
print(my_physical_variable)

[0.49496843 0.075648   0.99441966 0.66990802]


In [10]:
my_physical_variable = npr.random(4)
print(my_physical_variable)

[0.44128815 0.48055089 0.03025358 0.06241068]


Fortunately, __one can create reproducible random__, i.e. a way to get the same random values whenever the code is ran.

To this purpose, one must define a random number generator and __initialize it__ with the same initial _state_ for all executions:

In [11]:
rng = npr.default_rng(42)                 
my_physical_variable = rng.random(4)
print(my_physical_variable)

[0.77395605 0.43887844 0.85859792 0.69736803]


In [12]:
rng_new = npr.default_rng(42)
my_physical_variable = rng_new.random(4)
print(my_physical_variable)

[0.77395605 0.43887844 0.85859792 0.69736803]


In [66]:
rng_new = npr.default_rng(65)      # different seed
my_physical_variable = rng_new.random(4)
print(my_physical_variable)

[0.04739149 0.51822218 0.37485856 0.22867852]


Note that:

- defining the initial state returns a new instance that must be used to generate random numbers
- using this instance provides reproducible random numbers generation
- a different initial state gives different random numbers